[package]
name = "dream"
version = "0.1.0"
authors = ["bidhan-a <bidhan619@gmail.com>"]
edition = "2018"

[dependencies]
daggy = "0.6.0"
csv = "1.1.3"
crossbeam = "0.7.3"
crossbeam-utils = "0.7.2"
log = "0.4.8"
fern = "0.6.0"
chrono = "0.4.11"
uuid = { version = "0.8", features = ["v4"] }
